LanWebsite/Models/Booking.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.SeatDetail = new HashSet<SeatDetail>();
        }
    
        public int BookingID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string TicketType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatDetail> SeatDetail { get; set; }
    }
}

LanWebsite/Controllers/BillingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LanWebsite.Models;

namespace LanWebsite.Controllers
{
    public class BillingController : Controller
    {
        // GET: Billing
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Booking()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BookSeat(String User, String SeatID)
        {
            int seatID; // Init en integer variable der sættes til at være lig med det input fra Booking
            int users; // Init endnu en variable, der sættes til at være lig med User inputtet fra Booking siden

            if(int.TryParse(User, out int UserID) && int.TryParse(SeatID, out int SeatsID))
            {
                users = UserID;
                seatID = SeatsID;
                using (LanWebsiteEntities e = new LanWebsiteEntities())
                {
                    // Her laves der et objekt, hvilket bliver den der bruges til at få værdierne fra Databasen
                    SeatDetail seat = new SeatDetail();

                    /* 
                      Her laves der to variabler der går ind og sammenligner det input givet på hjemmesiden med den information der
                      står i vores SQL Database. Den værdi den får tilbage fra det bliver sat lig med den nye "seatDetails" variable 
                      og det samme sker der ved "isUser". 

                      De to mulige resultater enten et tal over 1 eller 0. Nul forekommer kun hvis det nummer der angives
                      ikke eksistere på databasen.
                    */
                    var seatDetails = (from r in e.SeatDetail where r.SeatID == seatID select r.SeatID).FirstOrDefault();
                    var isUser = (from r in e.Booking where r.BookingID == users select r.BookingID).FirstOrDefault();

                    // Her er lavet en try/catch, hvilket gør sådan hvis der skulle opstå en problem
                    // bliver execpetion "kastet" til console, så der kan ses hvad der gik galt
                    try
                    {
                        // If statement der tjekker om en af de to variabler ikke eksistere i databasne
                        if (seatDetails == 0 || isUser == 0)
                        {
                            // Logger problemet til DB
                            System.Diagnostics.Debug.WriteLine("Either the user or seat does not exist");

                            // Refresher siden
                            return View("Booking");
                        }
                        else
                        {
                            // Her køres der en Sql Query, som bruges til at opdatere den information der står inde på DB med den nye bord status.
                            e.Database.ExecuteSqlCommand("UPDATE SeatDetail SET BookingID='" + users + "', Status='selectedSeat' WHERE SeatID=" + seatID);
                            System.Diagnostics.Debug.WriteLine(seatDetails + " " + isUser);
                            return View("Booking");
                        }
                    }
                    catch (Exception ex)
                    {
                        // Her viser den hvis der skulle forekomme en fejl i Consolen
                        System.Diagnostics.Debug.WriteLine(ex);
                        return View("Index");
                    }

                }
            } else {
                return View("Booking");
            }
        }
            //if(User == null)
            // Forbindelse til databasen bliver oprettet

    }
}

LanWebsite/Views/Billing/Booking.cshtml
@model LanWebsite.Models.SeatStatus
@{
    ViewBag.Title = "Booking";
    LanWebsite.Models.SeatStatus status = new LanWebsite.Models.SeatStatus();
    LanWebsite.Classes.Settings settings = new LanWebsite.Classes.Settings();
}
<link href="~/Content/BookingPage.css" rel="stylesheet" />

<div class="container"><h1 class="header">Vælg Bord</h1></div>

<div id="bookingbody" class="container">
    <div id="holder">
        <ul id="place">
            @{
                <!-- Her starter vores for løkke, som er med til at lave vores borde ud fra informationerne gives i classen settings -->
                for (int i = 0; i < settings.rows; i++)
                {
                    for (int j = 0; j < settings.cols; j++)
                    {
                        <!-- Udregner bord nr. ud fra hvor den er -->
                        int seatNo = (i + j * settings.rows + 1);

                        <!-- Sætter størrelsen på højden og breden af bordene -->
                        String top = "top:" + (i * settings.seatHeight) + "px;";
                        String left = "left:" + (j * settings.seatWidth) + "px";

                        <!-- Her laves en string der angiver styling ud fra det angivet i "settings" classen -->
                        String className = settings.seatCss + " " + settings.rowCssPrefix + i + " " + settings.colCssPrefix + j;

                        <!-- Her placeres vores strings ind i en list element og henter information for en SQL Database -->
                        <li class="@className @status.GetStatus(seatNo)" style="@top @left"><a title="@seatNo"></a></li>
                    }
                }
            }
        </ul>
    </div>
</div>
<!-- Her laves vores knapper og billeder der fortæller hvad de forskellige farver betyder -->
<div class="BookingContent">
    <!-- Her er de farvet billeder -->
    <div id="expl">
        <ul id="seatDescription">
            <li style="background:url('../../Materials/Images/Booking/available.svg') no-repeat scroll 0 0 transparent;">Available Seat</li>
            <li style="background: url('../../Materials/Images/Booking/reserved.svg') no-repeat scroll 0 0 transparent;">Booked Seat</li>
            <li style="background: url('../../Materials/Images/Booking/selected.svg') no-repeat scroll 0 0 transparent;">Selected Seat</li>
        </ul>
    </div>
    <!-- Her laves knapperne der siger hvilke er valgte og alle der er reseveret og valgt -->
    <div id="buttons_pack">
        <input type="button" id="btnShowNew" value="Show Selected Seats" />
        <input type="button" id="btnShow" value="Show All" />
    </div>
</div>
<div class="BookingDiv">
    @using (Html.BeginForm("BookSeat", "Billing", FormMethod.Post))
    {
        @Html.TextArea("SeatID", new { id = "tableNr" })
        @Html.TextArea("User", new { placeholder = "UserID"})
        <button id="select" runat="server" OnServerClick="Button_Click">Click here</button>
    }
</div>

<script>

    // Script der siger hvorvidt det valgte bord er optaget
    $('.' + "@settings.seatCss").click(function () {
        var str = [];
        // Tjekker om det bord der blev trykket på har "selectedSeat" i sig
        if ($(this).hasClass("@settings.selectedSeatCss")) {
            alert('This seat is already reserved');
        }
        // Hvis ikke toggler den bordet farve til grøn og placere selected i dens klasse
        else {
            $(this).toggleClass("@settings.selectingSeatCss");
            $.each($('#place li.' + "@settings.selectingSeatCss" + ' a'), function (index, value) {
                str.push($(this).attr('title'));
            });
            document.getElementById('tableNr').innerHTML = str.join(", ");

        }
    });

    // Her tilføjes funktion til vores ene knap der viser hvilke borde der er valgte
    $('#btnShow').click(function () {
        var str = [];
        // Selector alle borde, som indeholder selectingSeat som klasse og adder dem til str listen.
        $.each($('#place li.' + "@settings.selectedSeatCss" + ' a, #place li.' + "@settings.selectingSeatCss" + ' a'), function (index, value) {
            str.push($(this).attr('title'));
        });
        // Sender en besked på hjemmesiden med listen af dem der er valgt
        alert(str.join(','));
    })

    // Den her har meget samme funktion som den før, her viser den dog alle der er valgte og reseveret
    $('#btnShowNew').click(function () {
        var str = [], item;
        $.each($('#place li.' + "@settings.selectingSeatCss" + ' a'), function (index, value) {
            item = $(this).attr('title');
            str.push(item);
        });
        alert(str.join(','));
    })


</script>

<!--
<script>
    var settings = {
        rows: 5,
        cols: 15,
        rowCssPrefix: 'row-',
        colCssPrefix: 'col-',
        seatWidth: 35,
        seatHeight: 35,
        seatCss: 'seat',
        selectedSeatCss: 'selectedSeat',
        selectingSeatCss: 'selectingSeat'
    };

    var init = function (reservedSeat) {
        var str = [], seatNo, className;
        for (i = 0; i < settings.rows; i++) {
            for (j = 0; j < settings.cols; j++) {
                seatNo = (i + j * settings.rows + 1);
                className = settings.seatCss + ' ' + settings.rowCssPrefix + i.toString() + ' ' + settings.colCssPrefix + j.toString();
                if ($.isArray(reservedSeat) && $.inArray(seatNo, reservedSeat) != -1) {
                    className += ' ' + settings.selectedSeatCss;
                }
                str.push('<li class="' + className + '" ' +
                    ' style="top:' + (i * settings.seatHeight).toString() + 'px;left:' + (j * settings.seatWidth).toString() + 'px">' + '<a title="' + seatNo + '"></a>' + '</li > ');}
                }
    $('#place').html(str.join(''));
            };
    //case I: Show from starting
    //init();

    //Case II: If already booked
    var bookedSeats = [5, 10, 25];
    init(bookedSeats);
</script>
-->

LanWebsite/Views/Billing/Index.cshtml
@*<link href="~/Content/BillingCSS.css" rel="stylesheet" />*@
<link href="~/Content/PricingTable.css" rel="stylesheet" />
@{
    ViewBag.Title = "Index";
}
<nav class="nav affix">
    <div class="container">
        <div class="logo">
            <a href="~/Home/Index">LANPARTY360</a>
        </div>
        <div id="mainListDiv" class="main_list">
            <ul class="navlinks">
                <li><a href="#">OM OS</a></li>
                <li><a href="#">BILLET</a></li>
            </ul>
        </div>
    </div>
</nav>
<!--
    Syed Sahar Ali Raza
  ========================	-->
<div id="generic_price_table">
    <section>
        <div class="container">
            <div class="row center-items">
                <h1 class="ticketTitle">Billet Typer</h1>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="generic_content clearfix">
                        <div class="generic_head_price clearfix">
                            <div class="generic_head_content clearfix">

                                <div class="head_bg"></div>
                                <div class="head">
                                    <span>Standard</span>
                                </div>

                            </div>
                            <div class="generic_price_tag clearfix">
                                <span class="price">
                                    <span class="currency">149.95 </span>
                                    <span class="month">kr</span>
                                </span>
                            </div>
                        </div>
                        <div class="generic_feature_list">
                            <ul>
                                <li><span>1</span> Plads</li>
                                <li><span>100</span> Mbps Internet</li>
                                <li><span>2</span> Gratis Toast</li>
                                <li><span>1</span> Kop Kaffe</li>
                            </ul>
                        </div>
                        <div class="generic_price_btn clearfix">
                            <a class="" href="">Vælg</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="generic_content clearfix">
                        <div class="generic_head_price clearfix">
                            <div class="generic_head_content clearfix">
                                <div class="head_bg"></div>
                                <div class="head">
                                    <span>VIP</span>
                                </div>
                            </div>
                            <div class="generic_price_tag clearfix">
                                <span class="price">
                                    <span class="currency">249.95 </span>
                                    <span class="month">kr</span>
                                </span>
                            </div>
                        </div>
                        <div class="generic_feature_list">
                            <ul>
                                <li><span>1</span> Plads</li>
                                <li><span>150</span> Mbps Internet</li>
                                <li><span>5</span> Gratis Toast</li>
                                <li><span>1</span> Reseveret Soveplads</li>
                            </ul>
                        </div>
                        <div class="generic_price_btn clearfix">
                            <a class="" href="">Vælg</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="generic_content clearfix">
                        <div class="generic_head_price clearfix">
                            <div class="generic_head_content clearfix">
                                <div class="head_bg"></div>
                                <div class="head">
                                    <span>ULTRA</span>
                                </div>
                            </div>
                            <div class="generic_price_tag clearfix">
                                <span class="price">
                                    <span class="currency">349.95 </span>
                                    <span class="month">kr</span>
                                </span>
                            </div>
                        </div>
                        <div class="generic_feature_list">
                            <ul>
                                <li><span>1 XL</span> Plads</li>
                                <li><span>200</span> Mbps Internet</li>
                                <li><span>10</span> Gratis Toast</li>
                                <li><span>Fri</span> Entré til Turneringer</li>
                            </ul>
                        </div>
                        <div class="generic_price_btn clearfix">
                            <a class="" href="~/Billing/Booking">Vælg</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="container">
        <div class="row">
            <p class="text-fill">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam vel nisi nulla. Nam eu finibus eros, ut sollicitudin purus. Nullam non dolor non est 
                auctor efficitur. Maecenas vitae leo facilisis, cursus velit vitae, sagittis purus. Ut a rhoncus tortor, at sagittis sem. Mauris eleifend nibh diam, 
                vel euismod ligula aliquet ut. 
            </p>
        </div>
    </div>
</div>